In [1]:
import pandas as pd
import numpy as np

In [2]:
x=pd.read_csv(r"C:\Users\DELL\Downloads\cleaned_all_phones.csv")

In [3]:
x

,phone_name,brand,os,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),...,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
0,Y6II Compact,Huawei,Android 5.1,5.00,720x1280,2200,Li-Po,2,2016-09-01,140.0,...,False,False,False,True,False,False,False,False,False,120.000
1,K20 plus,LG,Android 7.0,5.30,720x1280,2700,Li-Ion,2,2016-12-01,140.0,...,True,False,False,True,False,False,False,False,False,100.000
2,P8 Lite (2017),Huawei,Android 7.0,5.20,1080x1920,3000,Li-Ion,4,2017-01-01,147.0,...,True,False,False,True,False,False,False,False,False,420.000
3,Redmi Note 4,Xiaomi,Android 6.0,5.50,1080x1920,4100,Li-Po,4,2017-01-01,165.0,...,True,False,False,True,False,True,False,False,False,150.000
4,P10,Huawei,Android 7.0,5.10,1080x1920,3200,Li-Ion,4,2017-02-01,145.0,...,True,True,False,True,True,False,False,False,False,420.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,vivo Y77t,Vivo,Android 13,6.64,1080x2388,5000,Li-Po,8,2023-08-18,190.0,...,True,False,False,True,False,False,False,False,False,170.000
1508,11x,Realme,Android 13,6.72,1080x2400,5000,Li-Po,8,2023-08-23,190.0,...,True,False,False,True,False,False,False,False,False,182.880
1509,GT5,Realme,Android 13,6.74,1240x2772,5240,Li-Po,16,2023-08-28,205.0,...,True,True,False,False,True,False,False,False,False,380.000
1510,GT5 240W,Realme,Android 13,6.74,1240x2772,4600,Li-Po,24,2023-08-28,205.0,...,True,True,False,False,True,False,False,False,False,470.000
1511,vivo iQOO Z7 Pro,Vivo,Android 13,6.78,1080x2400,4600,Li-Po,8,2023-08-31,175.0,...,True,True,False,True,False,False,False,False,False,287.988

In [16]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   phone_name         1512 non-null   object
 1   brand              1512 non-null   object
 2   os                 1512 non-null   object
 3   inches             1512 non-null   float64
 4   resolution         1512 non-null   object
 5   battery            1512 non-null   int64
 6   battery_type       1512 non-null   object
 7   ram(GB)            1512 non-null   int64
 8   announcement_date  1512 non-null   object
 9   weight(g)          1512 non-null   float64
 10  storage(GB)        1512 non-null   int64
 11  video_720p         1512 non-null   bool
 12  video_1080p        1512 non-null   bool
 13  video_4K           1512 non-null   bool
 14  video_8K           1512 non-null   bool
 15  video_30fps        1512 non-null   bool
 16  video_60fps        1512 non-null   bool
 17  video_120fps       1512 non-null   bool
 18  video_240fps       1512 non-null   bool
 19  video_480fps       1512 non-null   bool
 20  video_960fps       1512 non-null   bool
 21  price(USD)         1512 non-null   float64
dtypes: bool(10), float64(3), int64(3), object(6)
memory usage: 156.6+ KB

In [17]:
#1 How many unique  mobile brands are there in the data provided
x1=x["brand"].unique()

In [18]:
x1

array(['Huawei', 'LG', 'Xiaomi', 'Sony', 'Oppo', 'Samsung', 'Lenovo',
       'Apple', 'Google', 'Honor', 'Realme', 'OnePlus', 'Vivo'],
      dtype=object)

In [19]:
len(x1)

13

In [21]:
#2 What is the average ram size of all the collected data
x1=x["ram(GB)"].mean()

In [22]:
x1

6.6838624338624335

In [26]:
#3 Which phone is having the maximum and minimum battery capacity

In [31]:
x.loc[x['battery'].idxmax()]

phone_name                   V6
brand                     Honor
os                   Android 10
inches                     10.4
resolution            1200x2000
battery                    7250
battery_type              Li-Po
ram(GB)                       8
announcement_date    2020-05-19
weight(g)                 480.0
storage(GB)                  64
video_720p                False
video_1080p                True
video_4K                  False
video_8K                  False
video_30fps                True
video_60fps               False
video_120fps              False
video_240fps              False
video_480fps              False
video_960fps              False
price(USD)                280.0
Name: 573, dtype: object

In [34]:
x.loc[x['battery'].idxmin()]

phone_name             iPhone 8
brand                     Apple
os                       iOS 11
inches                      4.7
resolution             750x1334
battery                    1821
battery_type             Li-Ion
ram(GB)                       2
announcement_date    2017-09-12
weight(g)                 148.0
storage(GB)                  64
video_720p                 True
video_1080p                True
video_4K                   True
video_8K                  False
video_30fps                True
video_60fps                True
video_120fps               True
video_240fps               True
video_480fps              False
video_960fps              False
price(USD)                210.0
Name: 62, dtype: object

In [9]:
#4 What is the maximum battery capacity provided by Huawei Company

x["battery"].max().loc["Huawei"]

AttributeError: 'int' object has no attribute 'loc'

In [19]:
# 5 Which Phone brand is providing the highest and lowest ram

x1=(x["ram(GB)"]==x["ram(GB)"].max())

In [22]:
x.loc[x1]["brand"]

1505     Xiaomi
1506    OnePlus
1510     Realme
Name: brand, dtype: object

In [21]:
x2=(x["ram(GB)"]==x["ram(GB)"].min())

In [23]:
x.loc[x2]["brand"]

27      Huawei
28     Samsung
69     Samsung
133     Huawei
182    Samsung
230    Samsung
236     Huawei
244     Xiaomi
304    Samsung
363         LG
550    Samsung
Name: brand, dtype: object

In [25]:
# 6 How many phones has android 7.0 as there operating system

In [6]:
x2=x.loc[x["os"]=="Android 7.0",["phone_name","os"]]

In [7]:
x2

            phone_name           os
1             K20 plus  Android 7.0
2       P8 Lite (2017)  Android 7.0
4                  P10  Android 7.0
5           Xperia XA1  Android 7.0
6             P10 Lite  Android 7.0
7             P10 Plus  Android 7.0
8     Xperia XA1 Ultra  Android 7.0
9             X power2  Android 7.0
13           Xperia L1  Android 7.0
16     Galaxy Xcover 4  Android 7.0
18          Galaxy S8+  Android 7.0
21             Harmony  Android 7.0
24                  Y7  Android 7.0
25         nova 2 plus  Android 7.0
26              nova 2  Android 7.0
31        Stylo 3 Plus  Android 7.0
33           X venture  Android 7.0
37       Galaxy J7 Max  Android 7.0
38    Galaxy J7 (2017)  Android 7.0
39       Galaxy J7 Pro  Android 7.0
40    Galaxy J5 (2017)  Android 7.0
41            Y7 Prime  Android 7.0
43           Q8 (2017)  Android 7.0
47        P9 lite mini  Android 7.0
49    Galaxy S8 Active  Android 7.0
50     Xperia XA1 Plus  Android 7.0
69    Galaxy J2 (2017)  Android 7.0
70        Mate 10 Lite  Android 7.0
77       Redmi Y1 Lite  Android 7.0
78            moto tab  Android 7.0
82               K320t  Android 7.0
91                 X4+  Android 7.0
109  Galaxy J7 Prime 2  Android 7.0

In [6]:
# 7 Which Phone is the oldest 

x1=x.loc[x["announcement_date"]==x1["announcement_date"].min()]

In [34]:
x1["phone_name"]

1    K20 plus
Name: phone_name, dtype: object

In [8]:
# 8 Which brand produced maximum number of phone in the given data
x1=x["brand"].min()
x.loc[x["brand"]==x1,["phone_name","brand"]].count()

phone_name    22
brand         22
dtype: int64

In [9]:
#9 Give the count of phones supporting 4k video,8k video,2k video

print(len(x.loc[x["video_4K"]==True,["brand","phone_name"]]))
x.loc[x["video_4K"]==True,["brand","phone_name"]]

801

        brand         phone_name
4      Huawei                P10
7      Huawei           P10 Plus
11       Sony         Xperia XZs
12       Sony  Xperia XZ Premium
15       Oppo            F3 Plus
...       ...                ...
1505   Xiaomi    Redmi K60 Ultra
1506  OnePlus          Ace 2 Pro
1509   Realme                GT5
1510   Realme           GT5 240W
1511     Vivo   vivo iQOO Z7 Pro

[801 rows x 2 columns]

In [11]:
print(len(x.loc[x["video_8K"]==True,["brand","phone_name"]]))
x.loc[x["video_8K"]==True,["brand","phone_name"]]

86

        brand           phone_name
466   Samsung        Galaxy S20 5G
467   Samsung       Galaxy S20+ 5G
468   Samsung     Galaxy S20 Ultra
470   Samsung  Galaxy S20 Ultra 5G
471   Samsung          Galaxy S20+
...       ...                  ...
1447     Vivo       vivo iQOO Neo8
1476     Vivo        vivo iQOO 11S
1497  Samsung       Galaxy Z Fold5
1504   Xiaomi           Mix Fold 3
1505   Xiaomi      Redmi K60 Ultra

[86 rows x 2 columns]

In [12]:
#10 How many phones supports Li-Po and Li-ion Battery
x1=x.loc[x["battery_type"]=="Li-Po",["phone_name"]].count()

In [13]:
x1

phone_name    1242
dtype: int64

In [14]:
x2=x.loc[x["battery_type"]=="Li-Ion",["phone_name"]].count()

In [15]:
x2

phone_name    270
dtype: int64

In [ ]:
# 11 How many sony phones supports 720x1280 resolution

In [16]:
# 12 Print a pivot table for finding the average weights ,total weights,based on brand and battery type

pd.pivot_table(x,index="brand",columns="battery_type",values=["weight(g)"],aggfunc=["mean"])

                    mean
               weight(g)
battery_type      Li-Ion       Li-Po
brand
Apple         186.227273         NaN
Google        190.666667  176.923077
Honor         165.333333  190.611570
Huawei        158.354839  187.556604
LG            154.851852  183.812500
Lenovo        190.142857  218.586207
OnePlus              NaN  191.553191
Oppo          157.833333  183.174603
Realme        166.833333  189.688742
Samsung       178.531250  196.727273
Sony          177.333333  178.769231
Vivo                 NaN  190.232143
Xiaomi        179.294118  195.906883